# Generated by Django 5.0.4 on 2024-05-13 09:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("comedy", "Comedy"),
                            ("drama", "Drama"),
                            ("horror", "Horror"),
                            ("action", "Action"),
                            ("romantic", "Romantic"),
                            ("scifi", "Sci-Fi"),
                            ("thriller", "Thriller"),
                            ("fantasy", "Fantasy"),
                            ("animation", "Animation"),
                            ("documentary", "Documentary"),
                            ("crime", "Crime"),
                            ("western", "Western"),
                            ("mystery", "Mystery"),
                            ("biography", "Biography"),
                            ("history", "History"),
                            ("music", "Music"),
                            ("family", "Family"),
                            ("war", "War"),
                            ("sport", "Sport"),
                            ("musical", "Musical"),
                            ("adventure", "Adventure"),
                            ("film-noir", "Film-Noir"),
                            ("short", "Short"),
                            ("tv-movie", "TV-Movie"),
                            ("game-show", "Game-Show"),
                            ("talk-show", "Talk-Show"),
                            ("news", "News"),
                            ("reality-tv", "Reality-TV"),
                            ("talk-show", "Talk-Show"),
                            ("reality-tv", "Reality-TV"),
                            ("news", "News"),
                            ("reality-tv", "Reality-TV"),
                        ],
                        max_length=255,
                    ),
                ),
                ("length", models.IntegerField()),
                ("image_card", models.ImageField(upload_to="movies_images/")),
                ("image_cover", models.ImageField(upload_to="movies_images/")),
                ("video", models.FileField(upload_to="movies_videos/")),
                ("movie_views", models.IntegerField(default=0)),
                ("uu_id", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
